INSERT INTO permissions(name)
VALUES
('USER_READ'),
('USER_CREATE'),
('USER_UPDATE'),
('USER_STATUS_UPDATE'),
('USER_DELETE'),

('ROLE_READ'),
('ROLE_CREATE'),
('ROLE_UPDATE'),
('ROLE_DELETE'),

('ROLE_ASSIGN'),
('ROLE_REMOVE'),

('MENU_READ'),
('MENU_CREATE'),
('MENU_UPDATE'),
('MENU_DELETE'),

('PERMISSION_READ'),
('PERMISSION_CREATE'),
('PERMISSION_UPDATE'),
('PERMISSION_DELETE');